# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-11 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgc', '0003_auto_20170311_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videogame',
            options={'verbose_name_plural': 'VideoGames'},
        ),
        migrations.AddField(
            model_name='videogame',
            name='slug',
            field=models.SlugField(default=' '),
            preserve_default=False,
        ),
    ]
