# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-13 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vgc', '0004_auto_20170311_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
