# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-13 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgc', '0005_remove_userprofile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
