# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-13 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgc', '0006_auto_20170313_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name_plural': 'Character'},
        ),
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='bio',
            field=models.CharField(help_text='Please enter the bio of the character.', max_length=512),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(help_text='Please enter the name of the character.', max_length=128),
        ),
        migrations.AlterField(
            model_name='character',
            name='url',
            field=models.URLField(blank=True, help_text='Please enter the URL of the character.'),
        ),
    ]
