# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-17 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgc', '0008_auto_20170317_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='picture',
            field=models.ImageField(blank=True, help_text='Add Video Game Picture', upload_to='game_images'),
        ),
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.ImageField(blank=True, help_text='Add Character Picture', upload_to='char_images'),
        ),
    ]
