# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-17 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgc', '0009_auto_20170317_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='name',
            field=models.CharField(help_text='Please Enter the videogame title', max_length=128, unique=True),
        ),
    ]
