# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-17 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vgc', '0010_auto_20170317_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listelement',
            name='character',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vgc.Character'),
        ),
    ]
